stages:
  - lint
  - unit
  - e2e
  - build

lint:
  stage: lint
  image: node:20
  script:
    - set -e
    - npm ci
    - npm run lint

unit_tests:
  stage: unit
  image: node:20
  variables:
    CYPRESS_INSTALL_BINARY: 0
  script:
    - set -e
    - npm ci
    - npm run test:unit

e2e_tests:
  stage: e2e
  image: cypress/browsers:node-22.15.0-chrome-135.0.7049.114-1-ff-137.0.2-edge-135.0.3179.85-1
  services:
    - name: mongo:7.0.4
      alias: mongo
  variables:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: password
  before_script:
    - set -e
    - apt-get update && apt-get install -y curl gnupg
    - curl -fsSL https://pgp.mongodb.com/server-7.0.asc | gpg --dearmor -o /usr/share/keyrings/mongodb-server-7.0.gpg
    - echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 main" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list
    - apt-get update && apt-get install -y mongodb-database-tools

    - npm install -g wait-on

    - rm -rf ../auth-server ../data-server
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lnu.se/1dv613/student/jl225vf/projects/auth-server.git ../auth-server
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lnu.se/1dv613/student/jl225vf/projects/data-server.git ../data-server

    - cd ../auth-server
    - echo "$TEST_PRIVATE_PEM" > test_private.pem
    - echo "$TEST_PUBLIC_PEM" > test_public.pem
    - echo "DEBUG - Contents of test_private.pem"
    - cat test_private.pem
    - echo "DEBUG - test_private.pem exists"
    - ls -l test_private.pem
    - npm ci
    - export DB_CONNECTION_STRING="mongodb://root:password@mongo:27017/auth_test?authSource=admin"
    - export ACCESS_TOKEN_PRIVATE_KEY_PATH="./test_private.pem"
    - export ACCESS_TOKEN_PUBLIC_KEY_PATH="./test_public.pem"
    - export ACCESS_TOKEN_LIFE="2h"
    - export REFRESH_TOKEN_KEY="$TEST_REFRESH_TOKEN_KEY"
    - export REFRESH_TOKEN_LIFE="2d"
    - export PORT=5053
    - npm run dev:ci > auth.log 2>&1 &
    - sleep 5
    - echo "=== Auth Server Logs (initial) ===" && cat auth.log

    - cd ../data-server
    - echo "$TEST_PUBLIC_PEM" > public.pem
    - npm ci
    - export DB_CONNECTION_STRING="mongodb://root:password@mongo:27017/data_test?authSource=admin"
    - export AUTH_TOKEN_SECRET_PATH="./public.pem"
    - export PORT=5054
    - npm run dev:ci > data.log 2>&1 &
    - sleep 5
    - echo "=== Data Server Logs (initial) ===" && cat data.log

    - cd ../web-server
    - npm ci
    - export VITE_AUTH_URL="http://localhost:5053/api/v1"
    - export VITE_DATA_URL="http://localhost:5054/api/v1"
    - npm run dev -- --port 4173 > vite.log 2>&1 &

    - npx wait-on --timeout 90000 http://localhost:4173 http://localhost:5053/api/v1 http://localhost:5054/api/v1

    - echo "=== Auth Server Logs ===" && tail -n 20 ../auth-server/auth.log || true
    - echo "=== Data Server Logs ===" && tail -n 20 ../data-server/data.log || true
    - echo "=== Vite Logs ===" && tail -n 20 vite.log || true

    - mongoimport --uri="mongodb://root:password@mongo:27017/data_test" --collection=fooditems --file=../data-server/data/clean.json --jsonArray --authenticationDatabase admin

  script:
    - set -e
    - npx cypress run --e2e

  artifacts:
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos
      - coverage/e2e

build:
  stage: build
  image: node:20
  script:
    - set -e
    - npm ci
    - npm run build
