stages:
  - lint
  - unit
  - e2e
  - build

lint:
  stage: lint
  image: node:20
  script:
    - npm ci
    - npm run lint

unit_tests:
  stage: unit
  image: node:20
  script:
    - npm ci
    - npm run test:unit

e2e_tests:
  stage: e2e
  image: cypress/browsers:node-20.10.0-chrome120-ff119-edge
  services:
    - mongo:7.0.4
  variables:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: password
  before_script:
    - apt-get update && apt-get install -y curl gnupg mongodb-database-tools

    # Clone auth-server and data-server
    - rm -rf ../auth-server ../data-server
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lnu.se/1dv613/student/jl225vf/projects/auth-server.git ../auth-server
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lnu.se/1dv613/student/jl225vf/projects/data-server.git ../data-server

    # Start auth-server
    - cd ../auth-server
    - echo "$TEST_PRIVATE_PEM" > test_private.pem
    - echo "$TEST_PUBLIC_PEM" > test_public.pem
    - npm ci
    - DB_CONNECTION_STRING="mongodb://mongo:27017/auth_test" \
      ACCESS_TOKEN_PRIVATE_KEY_PATH="./test_private.pem" \
      ACCESS_TOKEN_PUBLIC_KEY_PATH="./test_public.pem" \
      ACCESS_TOKEN_LIFE="2h" \
      REFRESH_TOKEN_KEY="$TEST_REFRESH_TOKEN_KEY" \
      REFRESH_TOKEN_LIFE="2d" \
      PORT=5053 \
      npm run dev &

    # Start data-server
    - cd ../data-server
    - echo "$TEST_PUBLIC_PEM" > public.pem
    - npm ci
    - DB_CONNECTION_STRING="mongodb://mongo:27017/data_test" \
      AUTH_TOKEN_SECRET_PATH="./public.pem" \
      PORT=5054 \
      npm run dev &

    # Import data for fooditems collection
    - sleep 5
    - mongoimport --uri="mongodb://mongo:27017/data_test" --collection=fooditems --file=../data-server/data/clean.json --jsonArray

    # Start web-server
    - cd ../web-server
    - npm ci
    - VITE_AUTH_URL="http://localhost:5053/api/v1" \
      VITE_DATA_URL="http://localhost:5054/api/v1" \
      npm run dev -- --port 4173 &
    - sleep 10

  script:
    - npx cypress run --e2e

  artifacts:
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos
      - coverage/e2e

build:
  stage: build
  image: node:20
  script:
    - npm ci
    - npm run build
