stages:
  - lint
  - test:unit

variables:
  VITE_AUTH_URL: "http://localhost:8080"

lint:
  stage: lint
  image: node:20
  script:
    - npm ci
    - npm run lint

test:unit:
  stage: test:unit
  image: node:20
  script:
    - npm ci
    - npm run test:unit
