name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run lint

  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      CYPRESS_INSTALL_BINARY: 0
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run test:unit

  test-e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    steps:
      - uses: actions/checkout@v4

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 7
          mongodb-username: root
          mongodb-password: password

      - name: Install database tools & wait-on
        run: |
          sudo curl -fsSL https://pgp.mongodb.com/server-7.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-server-7.0.gpg
          echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-database-tools
          npm install -g wait-on

      - name: Clone Auth & Data Servers
        run: |
          git clone https://github.com/JuliaLind/1dv613-auth-server ../auth-server
          git clone https://github.com/JuliaLind/1dv613-data-server ../data-server

      - name: Start Auth Server
        run: |
          echo "${{ secrets.TEST_PRIVATE_PEM }}" > ../auth-server/test_private.pem
          cd ../auth-server
          npm ci
          DB_CONNECTION_STRING="mongodb://root:password@localhost:27017/auth_test?authSource=admin" \
          ACCESS_TOKEN_PRIVATE_KEY_PATH="$(pwd)/test_private.pem" \
          ACCESS_TOKEN_LIFE="2h" \
          REFRESH_TOKEN_KEY="${{ secrets.TEST_REFRESH_TOKEN_KEY }}" \
          REFRESH_TOKEN_LIFE="2d" \
          PORT=5053 \
          npm run dev:ci > auth.log 2>&1 &

      - name: Start Data Server
        run: |
          echo "${{ secrets.TEST_PUBLIC_PEM }}" > ../data-server/public.pem
          cd ../data-server
          npm ci
          DB_CONNECTION_STRING="mongodb://root:password@localhost:27017/data_test?authSource=admin" \
          AUTH_TOKEN_SECRET_PATH="$(pwd)/public.pem" \
          PORT=5054 \
          npm run dev:ci > data.log 2>&1 &

      - name: Start Web Server & Wait
        run: |
          npm ci
          VITE_AUTH_URL="http://localhost:5053/api/v1" \
          VITE_DATA_URL="http://localhost:5054/api/v1" \
          npm run dev -- --port 4173 > vite.log 2>&1 &

          npx wait-on --timeout 90000 http://localhost:4173 http://localhost:5053/api/v1 http://localhost:5054/api/v1

          echo "=== Auth Logs ===" && tail -n 20 ../auth-server/auth.log || true
          echo "=== Data Logs ===" && tail -n 20 ../data-server/data.log || true
          echo "=== Vite Logs ===" && tail -n 20 vite.log || true

      - name: Import Mongo Seed
        run: |
          mongoimport --uri="mongodb://root:password@localhost:27017/data_test" \
          --collection=fooditems --file=../data-server/data/clean.json \
          --jsonArray --authenticationDatabase=admin

      - name: Run Cypress E2E Tests
        run: |
          npx cypress run --e2e

      - name: Upload Cypress Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-artifacts
          path: |
            cypress/screenshots
            cypress/videos
            coverage/e2e

  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    env:
      VITE_AUTH_URL: "https://julia-lnu.duckdns.org/auth/api/v1"
      VITE_DATA_URL: "https://julia-lnu.duckdns.org/data/api/v1"
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/

  deploy:
    name: Deploy Web App via Docker over SSH
    runs-on: ubuntu-latest
    needs: [lint, test-unit, test-e2e, build]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: Verify dist folder exists
        run: ls -la dist

      - name: Start SSH agent and add private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add droplet to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.PRODUCTION_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Set Docker host
        run: echo "DOCKER_HOST=ssh://root@${{ secrets.PRODUCTION_HOST }}" >> $GITHUB_ENV

      - name: Deploy via Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d --build
